trigger:
- main

pool:
  vmImage: riyaldn/my_image.1

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'riyaldn/boring_meitner'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
